title = "Code Vibe Blogs"
baseURL = 'https://blog.mankiratsingh.com/'

# This is what goes in <html lang="">
languageCode = 'en-gb'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# traditional way: theme component resides in directory 'themes'
# theme = "hugo-blog-awesome"

# modern way: pull in theme component as hugo module
[module]
  # Uncomment the next line to build and serve using local theme clone declared in the named Hugo workspace:
  workspace = "hugo-blog-awesome.work"
  [module.hugoVersion]
    extended = true
    min = "0.87.0"
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = false

# [services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
  [services.googleAnalytics]
    id = 'G-0DGJGVK6DD' # G-MEASUREMENT_ID

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next two lines
  # [services.disqus]
    # shortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/en"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags'
    weight = 30
  [[Languages.en-gb.menu.main]]
    pageRef="portfolio"
    name = 'mankiratsingh.com'
    url = 'https://mankiratsingh.com'
    weight = 40

[Languages.en-gb.params]
  sitename = "Tech Today Blogs" # site name
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Blog by Mankirat Singh"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/time/format/ for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-gb.params.author]
  # avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Code Vibe Blogs"
  name = "Mankirat Singh"
  description = "Hi There! I am Mankirat Singh, a 3rd year computer engineering student and a tech enthusiast. Starting these blogs out of curiosity to know hugo and document my coding journey."


###################################################################

# Allow to override `browserconfig.xml` params (configuration for windows embedded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  description = "Hi There! I am Mankirat Singh, a 3rd year computer engineering student and a tech enthusiast. Starting these blogs out of curiosity to know hugo and document my coding journey."
  author = "Mankirat Singh"
  # author = ["Me", "You"] # multiple authors

  defaultTheme = "auto"
  # disableThemeToggle = true
  # ShowShareButtons = true
  ShowReadingTime = true
  # disableSpecial1stPost = true
  # displayFullLangName = true
  # ShowPostNavLinks = true
  # ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  # comments = false
  # images = ["images/papermod-cover.png"]

  [params.profileMode]
    enabled = false
    title = "PaperMod"
    imageUrl = "#"
    imageTitle = "my image"
    # imageWidth = 120
    # imageHeight = 120
    [[params.profileMode.buttons]]
      name = "Archives"
      url = "archives"
    [[params.profileMode.buttons]]
      name = "Tags"
      url = "tags"

  [params.homeInfoParams]
    Title = "Hi, I am Mankirat Singh"
    Content = """👋 Welcome to landing page of my code vibe blogs!<br>
      Here I write about the code I vibe on :D<br>
      For more info about me, visit [mankiratsingh.com](https://mankiratsingh.com).
    """

  [[params.socialIcons]]
    name = "github"
    title = "MankiratSingh1315"
    url = "https://github.com/MankiratSingh1315"
  [[params.socialIcons]]
    name = "linkedin"
    title = "mankiratsingh1315"
    url = "https://www.linkedin.com/in/mankiratsingh1315/"
  [[params.socialIcons]]
    name = "X"
    title = "@Mankirat1315"
    url = "https://x.com/Mankirat1315"  #   safari_pinned_tab = "<link / abs url>"

    # url = "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"
  # [[params.socialIcons]]
  #   name = "KoFi"
  #   title = "Buy me a Ko-Fi :)"
  #   url = "https://ko-fi.com/adityatelange"

  [params.editPost]
    URL = "https://github.com/MankiratSingh1315/blogs/tree/main/content/en"
    Text = "Suggest Changes"
    appendFilePath = true

  # [params.label]
  #   iconSVG = '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  #   text = "Home"
  #   icon = "icon.png"
  #   iconHeight = 35

  [params.analytics.google]
    SiteVerificationTag = "G-0DGJGVK6DD" # G-MEASUREMENT_ID

  [params.assets]
    disableHLJS = true
  #   favicon = "<link / abs url>"
  #   favicon16x16 = "<link / abs url>"
  #   favicon32x32 = "<link / abs url>"
  #   apple_touch_icon = "<link / abs url>"


  # [params.cover]
  #   hidden = true
  #   hiddenInList = true
  #   hiddenInSingle = true

  # [params.fuseOpts]
  #   isCaseSensitive = false
  #   shouldSort = true
  #   location = 0
  #   distance = 1000
  #   threshold = 0.4
  #   minMatchCharLength = 0
  #   keys = ["title", "permalink", "summary", "content"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
